Repository TigerHacks/app-ios, pull requests merged in 2018-09, with the labels that each got.

#21 Added Cosmetic UI Star, Favorite and Unfavorite
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/Contents.json
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/favoriteStar.imageset/Contents.json
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/favoriteStar.imageset/star-4.png
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/favoriteStar.imageset/star-6.png
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/favoriteStar.imageset/star-7.png
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/unfavoriteStar.imageset/Contents.json
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/unfavoriteStar.imageset/star-3.png
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/unfavoriteStar.imageset/star-8.png
  TigerHacks-App/TigerHacks-App/Assets.xcassets/Favorites Buttons/unfavoriteStar.imageset/star.png
  TigerHacks-App/TigerHacks-App/Base.lproj/Main.storyboard
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizeDetailViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizesViewController.swift
Labels: 1.1

#22 Added swiftlint functionality for Travis
  TigerHacks-App/.swiftlint.yml
  TigerHacks-App/TigerHacks-App.xcodeproj/project.pbxproj
  TigerHacks-App/TigerHacks-App/AppDelegate.swift
  TigerHacks-App/TigerHacks-App/Extensions.swift
  TigerHacks-App/TigerHacks-App/Model/Constants.swift
  TigerHacks-App/TigerHacks-App/Model/Event.swift
  TigerHacks-App/TigerHacks-App/Model/Mentor.swift
  TigerHacks-App/TigerHacks-App/Model/Model.swift
  TigerHacks-App/TigerHacks-App/Model/Prize.swift
  TigerHacks-App/TigerHacks-App/Model/Sponsor.swift
  TigerHacks-App/TigerHacks-App/Views/Map/MapTableViewCell.swift
  TigerHacks-App/TigerHacks-App/Views/Map/MapViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizeDetailViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizeTableViewCell.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizesViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Resources/ResourcesTableViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Resources/TigerTalksDetailViewController.swift
  TigerHacks-App/TigerHacks-App/Views/RootViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Schedule/EventDetailViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Schedule/ScheduleTableViewCell.swift
  TigerHacks-App/TigerHacks-App/Views/Schedule/ScheduleViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Sponsors/AllMentorTableViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Sponsors/MentorTableViewCell.swift
  TigerHacks-App/TigerHacks-App/Views/Sponsors/SponsorCollectionViewCell.swift
  TigerHacks-App/TigerHacks-App/Views/Sponsors/SponsorsCollectionViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Sponsors/SponsorsDetailViewController.swift
  TigerHacks-App/TigerHacks-App/install_swiftlint.sh
Labels: 1.1, enhancement

#35 Implemented Schedule API
  TigerHacks-App/TigerHacks-App/Base.lproj/Main.storyboard
  TigerHacks-App/TigerHacks-App/Model/Model.swift
  TigerHacks-App/TigerHacks-App/Views/Map/MapViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Schedule/ScheduleViewController.swift
Labels: 2.0, enhancement, untest

#34 Implemented Prize API
  TigerHacks-App/TigerHacks-App/Model/Model.swift
  TigerHacks-App/TigerHacks-App/Model/Prize.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizeDetailViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizesViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Resources/ResourcesTableViewController.swift
Labels: 2.0, enhancement, untest

#46 Added Support for XR and XS Max
  TigerHacks-App/TigerHacks-App/Model/Constants.swift
  TigerHacks-App/TigerHacks-App/Model/Model.swift
Labels: 2.0, bug, ui

#40 Fixed Event Cell UI
  TigerHacks-App/TigerHacks-App/Base.lproj/Main.storyboard
Labels: 2.0, bug, ui

#44 Model Cleanup and Notifications
  TigerHacks-App/TigerHacks-App.xcodeproj/project.pbxproj
  TigerHacks-App/TigerHacks-App/AppDelegate.swift
  TigerHacks-App/TigerHacks-App/Model/Model.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizeDetailViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Prizes/PrizesViewController.swift
  TigerHacks-App/TigerHacks-App/Views/Schedule/ScheduleViewController.swift
Labels: 2.0, bug, untest
